# -*- coding: utf-8 -*-
"""Data-301-Hello-World.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqBnePbmmNjNSnq9d4CQxAjuDChKaeCO
"""

a=10
b=10

a+b